---
source: crates/ruff_linter/src/rules/ruff/mod.rs
---
RUF006.py:6:5: RUF006 Store a reference to the return value of `asyncio.create_task`
  |
4 | # Error
5 | def f():
6 |     asyncio.create_task(coordinator.ws_connect())  # Error
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ RUF006
  |

RUF006.py:11:5: RUF006 Store a reference to the return value of `asyncio.ensure_future`
   |
 9 | # Error
10 | def f():
11 |     asyncio.ensure_future(coordinator.ws_connect())  # Error
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ RUF006
   |

RUF006.py:68:12: RUF006 Store a reference to the return value of `asyncio.create_task`
   |
66 | # Error
67 | def f():
68 |     task = asyncio.create_task(coordinator.ws_connect())
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ RUF006
   |

RUF006.py:91:5: RUF006 Store a reference to the return value of `asyncio.create_task`
   |
89 | def f():
90 |     loop = asyncio.get_running_loop()
91 |     loop.create_task(coordinator.ws_connect())  # Error
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ RUF006
   |


